services:
  scylladb:
    image: scylladb/scylla
    container_name: telepathy-scylladb
    command: --smp 1 --memory 1G --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042"
      - "10000:10000"
    volumes:
      - scylla-data:/var/lib/scylla
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: telepathy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

#  scylla-manager:
#    image: scylladb/scylla-manager
#    container_name: telepathy-scylla-manager
#    ports:
#      - "8080:8080"
#    environment:
#      - CLUSTER_NAME=telepathy
#      - SCYLLA_MANAGER_USERNAME=admin
#      - SCYLLA_MANAGER_PASSWORD=admin123
#      - SCYLLA_CONTACT_POINTS=telepathy-scylladb
#    restart: unless-stopped

name: telepathy_docker
volumes:
  scylla-data:
  redis-data: